module.exports = [
  {
    sku: "905284114-4",
    name: "Fèi",
    price: 20,
    description: "vestibulum ante ipsum primis in faucibus orci luctus",
    "imageUrl": "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/99997.tif&wid=1800&cvt=jpeg",
    inventory: 67,
    category: "winter",
    size: "medium",
    rating: 1,
  },
  {
    sku: "975257029-1",
    name: "Hélèna", "price": 86,
    description: "fermentum donec ut mauris eget massa tempor convallis",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/99299.tif&wid=1800&cvt=jpeg",
    inventory: 99,
    category: "fall",
    size: "small",
    rating: 2,
  },
  {
    sku: "538286600-7",
    name: "Gérald", "price": 51,
    "description": "donec vitae nisi nam ultrices",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/99118.tif&wid=1800&cvt=jpeg",
    inventory: 60,
    category: "fall",
    size: "medium",
    rating: 3,
  },
  {
    sku: "689358481-4",
    name: "Vénus",
    price: 58,
    description: "et eros vestibulum ac est lacinia nisi venenatis tristique fusce",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/93786.tif&wid=1800&cvt=jpeg",
    inventory: 95,
    category: "winter",
    size: "small",
    rating: 4,
  },
  {
    sku: "806304873-3",
    name: "Aloïs",
    price: 27,
    description: "convallis morbi odio odio elementum eu interdum eu",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/78449.tif&wid=1800&cvt=jpeg", "inventory": 89,
    category: "winter",
    size: "large",
    rating: 5,
  },
  {
    sku: "203918559-3",
    name: "Hélèna",
    price: 76,
    description: "turpis integer aliquet massa id lobortis convallis tortor risus dapibus",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/66522.tif&wid=1800&cvt=jpeg",
    inventory: 47,
    category: "winter",
    size: "medium",
    rating: 5,
  },
  {
    sku: "221771074-5",
    name: "Réjane",
    price: 1,
    description: "justo eu massa donec dapibus duis at velit",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/74015.tif&wid=1800&cvt=jpeg",
    inventory: 77,
    category: "winter",
    size: "large",
    rating: 4,
  },
  {
    sku: "204448826-4",
    name: "Annotée",
    price: 38,
    description: "neque libero convallis eget eleifend luctus ultricies eu",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/88118.tif&wid=1800&cvt=jpeg",
    inventory: 18,
    category: "winter",
    size: "large",
    rating: 3,
  },
  {
    sku: "997951449-3",
    name: "Mylène",
    price: 68,
    description: "elit proin risus praesent lectus vestibulum quam sapien",
    imageUrl: "https://ii.sundancecatalog.com/fcgi-bin/iipsrv.fcgi?FIF=/images/sundance/source/products/en_us/source/66522.tif&wid=1800&cvt=jpeg",
    inventory: 95,
    category: "winter",
    size: "medium",
    rating: 2,
  },
];
